### PR TITLE
refactor: Use Array#fetch instead of Array#[] to resolve type errors

### PR DESCRIPTION
**Pull request by tk0miya**
47 -> 22

Note: This contains https://github.com/soutaro/steep/pull/1286

### CODE REVIEW

**Review by soutaro — APPROVED** [review]
Thanks! 🎉

**Comment by tk0miya** [comment]
I merged the main branch to this PR to resolve conflicts and to make this easy to review.

**Comment by soutaro** [comment]
Oops... force merge race...

**Comment by tk0miya** [comment]
😓  Don't mind. Thank you for reviewing and merging!

**Pull request merged**
